name: Build Windows EXE
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build EXE
        run: npm run build:win

      - name: Upload Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: heckerexe-windows
          path: dist/*.exe
